<a href="https://colab.research.google.com/github/Ruoro/hello-world/blob/main/Tensorflowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- artificial intelligence
- machine learning 
- deep learning

What to learn 
1. tensorflow basicsand fundamentals
2. preprocessing data
3. building and using pretrained models
4. fitting a model to the data    


- the approach is experimentation



# introduction to tensors

In [1]:
# import tensorflow
import tensorflow as tf
print (tf.__version__)

2.7.0


In [2]:
# create tensors with tf.constant
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions in a tensor
scalar.ndim

0

In [4]:
# create a vector
vector= tf.constant ([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the number of dimension of a vector
vector.ndim

1

In [7]:
# create a matrix
matrix = tf.constant([[2,10],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 7, 10]], dtype=int32)>

In [8]:
# check the dimensions of a matrix
matrix.ndim

2

In [10]:
# create a noter matrix
another_m = tf.constant([[10., 7.],
                         [3., 2.],
                         [8., 9.]], dtype = tf.float16)
another_m 

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
# check the number of dimensions 
another_m.ndim

2

In [15]:
# lets create a tensor
tensor= tf.constant([[[1, 2, 3,],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                      [16, 17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

What we've created so far 
- scalar: a single number
- vector: a number with direction
- matrix: a 2dimensional array of numbers
- tensor: a n-dimension array of number

### Tf.variable

In [20]:
 # create a tensor with tf.variable
 changable_tensor = tf.Variable([10,7])

 unchangable_tensor = tf.constant([7, 10])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [18]:
# lets change elements in changable_tensor
changable_tensor[0] =  7
changable_tensor

TypeError: ignored

In [19]:
# the correct way to do this is with .assign
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### create random tensors

In [28]:
# create random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = tf.random.normal(shape = (3,2))

# are they equal
random_1, random_2, random_1 == random_2



(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.11539967, -1.2651926 ],
        [ 0.7150141 , -0.8639476 ],
        [ 0.06240448,  0.20244198]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### shuffle the order of elements in a tensor

In [30]:
# valuable when you wnat to shuffle your data 
not_shuffled = tf.constant([[10,7],
                            [3,2],
                            [9, 3]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 9,  3]], dtype=int32)>

In [35]:
# shuffle our not shuffled 
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 9,  3]], dtype=int32)>